Create genre endpoints
RedberryInternship/movie-quotes-api-Domianidze pull request #10
Opened 2022-08-06 12:24 UTC by Domianidze

2022-08-06 15:06 UTC, giunashvili commented on src/controllers/genre-controller.ts
> +import { Request, Response, NextFunction } from 'express'
It would have been okay for genres to be static and not crud-ed

2022-08-06 15:10 UTC, giunashvili requested changes

2022-08-06 15:10 UTC, giunashvili commented on src/controllers/quote-controller.ts
> +        (movieQuote: any) => movieQuote.data !== quote._id
No any

2022-08-06 15:10 UTC, giunashvili commented on src/mail/views/verify-account-ge.handlebars
>          </div>
@Domianidze 
Sandro I think it will be better to have here style tag and all the styles to go there.
Do that way if you want. Just think it will be cleaner approach.

2022-08-06 15:43 UTC, Domianidze commented on src/controllers/genre-controller.ts
> +import { Request, Response, NextFunction } from 'express'
I am not really sure how to have static data in mongodb

2022-08-06 15:45 UTC, Domianidze commented on src/mail/views/verify-account-ge.handlebars
>          </div>
Yes, it would definitely be cleaner that way and I will do it like that next time but please don't make me change it, it would be such a chore :D

2022-08-07 07:22 UTC, giunashvili commented on src/controllers/genre-controller.ts
> +import { Request, Response, NextFunction } from 'express'
No not in mongodb. you'll have for example config/movie-quotes.ts where you'd put movie quotes configurations. and one of them would be just genres array

2022-08-07 07:24 UTC, giunashvili approved these changes

2022-08-07 07:24 UTC, merged